org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21.1,)

parchment_minecraft=1.21
parchment_version=2024.07.28

mod_id=dragonrise_reforge
mod_name=DragonRise:Reforge
mod_license=MIT
mod_version=1.4.1.01-20260619
mod_group_id=com.redabysslucia

mod_authors=red_abyss_lucia, CJY2, LY01, boy1145141919810, twosomebody, LOL_141, CHINACAT_2025, XingYu
mod_description=What was your mission in Shanghai!
